# Generated by Django 5.0.2 on 2024-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controle_contas_pagamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagamento',
            name='data',
            field=models.DateField(help_text='Informe quando sera o pagamento'),
        ),
    ]
