# Generated by Django 5.0.2 on 2024-02-15 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Address', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cidade',
            field=models.CharField(help_text='Digite a Cidade', max_length=255, null=True),
        ),
    ]
