# Generated by Django 5.0.2 on 2024-02-15 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Contatos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contatos',
            options={'verbose_name_plural': 'Contatos'},
        ),
        migrations.AlterField(
            model_name='contatos',
            name='datanasc',
            field=models.DateField(help_text='data de nascimento do contato', verbose_name='Data Nasc.'),
        ),
    ]
