# Generated by Django 5.0.2 on 2024-02-23 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vencimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorTotal', models.DecimalField(decimal_places=2, help_text='Digite o valor total a pagar', max_digits=5)),
                ('dataPagamento', models.DateField(help_text='Informe a data em que foi pago')),
                ('dataVencimento', models.DateField(help_text='Informe a data que venceu o pagamento')),
                ('valorPago', models.DecimalField(decimal_places=2, default=0, help_text='Informe o valor pago', max_digits=5)),
                ('statusPagamento', models.CharField(choices=[('1', 'Pagamento Pendente'), ('2', 'Pagamento parcial'), ('3', 'Pagamento Completo')], default='1', max_length=15)),
                ('tipo', models.CharField(choices=[('1', 'Dinheiro'), ('2', 'Cartão de Debito'), ('3', 'Cartao de Credito'), ('4', 'PIX'), ('5', 'Boleto')], default='4', max_length=15)),
            ],
        ),
    ]
